# Generated by Django 5.1.6 on 2025-03-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='interests',
            field=models.JSONField(default=list),
        ),
    ]
