# Generated by Django 5.1.7 on 2025-03-30 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
    ]
